### ISSUE TITLE
maybe bug in receive function

### ISSUE THREAD

**Issue by splov77** [flakey-bit/ClearScriptDebugging#2]
I think the buffer array always gets added in its entirety to the bytes list irrespective of the number of bytes received...maybe could wrap the buffer in another ArraySegment using the receiveResult count:
  do
            {
                var ba = new byte[8192];
                receiveResult = await sock.ReceiveAsync(new ArraySegment<byte>(ba), token);
                var buffer = new ArraySegment<byte>(ba, 0, receiveResult.Count);
                bytes.AddRange(buffer);
            } while (!receiveResult.EndOfMessage);

**Comment by flakey-bit** [comment]
You are quite right. However this is only demo code (not supposed to be production ready).
